In [1]:
import numpy as np
import pandas as pd

In [ ]:
dict = {
    "Name" : ["Sabuj","Ram","Subham"],
    "Marks" : [99,68,87],
    "City" : ['kolkata','Naipur','Egra',]
}

df = pd.DataFrame(dict)
df.to_csv('Friend.csv') # the csv file contains indices
df.to_csv('Friend_False_index.csv',index=False) # indices will not be there

     Name  Marks     City
0   Sabuj     99  kolkata
1     Ram     68   Naipur
2  Subham     87     Egra

In [ ]:
import pandas as pd
dict = {
    "Name" : ["Sabuj","Ram","Subham"],
    "Marks" : [99,68,87],
    "City" : ['kolkata','Naipur','Egra',]
}
df = pd.DataFrame(dict)
df.head(2) # will show the first two rows
df.tail(2) # will show the last two rows

df.describe() # ---
# It will print the following data


#           Marks
# count	3.000000
# mean	84.666667
# std	15.631165
# min	68.000000
# 25%	77.500000
# 50%	87.000000
# 75%	93.000000
# max	99.000000

           Marks
count   3.000000
mean   84.666667
std    15.631165
min    68.000000
25%    77.500000
50%    87.000000
75%    93.000000
max    99.000000